package com.teaguecole.planttracker.db

import com.teaguecole.planttracker.Plant

/**
 * Repository pattern — a single place for all database operations.
 *
 * This lives in commonMain so both Android and iOS use the same logic.
 * It depends on PlantDatabase (generated by SQLDelight from our .sq file)
 * and maps between the generated PlantEntity and our Plant data class.
 */
class PlantRepository(private val database: PlantDatabase) {

    private val queries = database.plantQueries

    fun getAllPlants(): List<Plant> {
        return queries.getAllPlants().executeAsList().map { entity ->
            Plant(
                id = entity.id,
                name = entity.name,
                location = entity.location,
                photoUri = entity.photoUri,
                lastWateredDate = entity.lastWateredDate,
                wateringInterval = entity.wateringIntervalDays.toInt()
            )
        }
    }

    fun insertPlant(plant: Plant) {
        queries.insertPlant(
            id = plant.id,
            name = plant.name,
            location = plant.location,
            photoUri = plant.photoUri,
            lastWateredDate = plant.lastWateredDate,
            wateringIntervalDays = plant.wateringInterval.toLong()
        )
    }

    fun markAsWatered(id: String) {
        // Clock.System is from kotlinx-datetime — a KMP library that gives you
        // cross-platform time. toEpochMilliseconds() stores it as a Long (which
        // is what our database column expects via INTEGER type).
        val now = kotlin.time.Clock.System.now().toEpochMilliseconds()
        queries.markAsWatered(lastWateredDate = now, id = id)
    }

    fun deletePlant(id: String) {
        queries.deletePlant(id)
    }
}
